### ISSUE TITLE
Debugger Not Connected

### ISSUE THREAD

**Issue by halsten** [zodiacon/WinDbgX#2]
Compiles fine, no problems whatsoever. I open the GUI, everything is disabled and it says at the status bar that Debugger not connected. Any ideas? Very nice project indeed. Would love to actually be able to test this.

--halsten

**Comment by zodiacon** [comment]
Sorry... you need the DLLs for the debugger engine and extensions from the debugging tools for Windows (or take from the release I provide)

**Comment by halsten** [comment]
I would have done that, but you only provided 64bit version. I would like to use it on my VM which is 32bit.

**Comment by zodiacon** [comment]
Then you'll have to copy the relevant files from c:\Program Files (x86)\Windows Kits\10\Debuggers\x86

**Comment by zodiacon** [comment]
My bad - I'll try to add an x86 version

**Comment by halsten** [comment]
No problem, I can copy any DLL from that directory. I already have WinDBG installed. Can you let me know which DLLs should I copy?

**Comment by zodiacon** [comment]
Just look at the x64 version - the exact same DLLs. basically that's the DLLs in the root folder and the extensions sub folders

**Comment by halsten** [comment]
Thanks! I guess you can close this issue now.

**Comment by halsten** [comment]
Sorry to open it again, but that didn't help. Copying all the necessary files and folders did not help.

**Comment by zodiacon** [comment]
I'll get an x86 release as soon as I can. In the meantime, you can test on your dev machine (x64). It doesn't install anything or interfere with anything.
